import { StyleSheet } from "react-native";
import { COLORS, SIZES } from "../constants/themes";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  header: {
    backgroundColor: COLORS.white,
    borderBottomLeftRadius: SIZES.radiusLarge,
    borderBottomRightRadius: SIZES.radiusLarge,
    padding: SIZES.padding,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: SIZES.padding,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  avatarPlaceholder: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: COLORS.primary,
  },
  appName: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.primary,
  },
  appSub: {
    fontSize: 12,
    color: COLORS.textDark,
    opacity: 0.7,
  },
  listWrapper: {
    flex: 1,
    paddingHorizontal: SIZES.padding,
    paddingBottom: 90,
  },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: SIZES.radiusMedium,
    flex: 1,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    overflow: "hidden",
  },
  flatListContent: {
    padding: SIZES.padding,
  },
  listItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 14,
  },
  listItemBorder: {
    borderBottomWidth: 1,
    borderBottomColor: "#F0F5FA",
  },
  listLeft: {
    flex: 1,
    justifyContent: "center",
    gap: 6,
  },
  listRight: {
    flex: 1,
    alignItems: "flex-end",
    justifyContent: "center",
    gap: 6,
  },
  listZone: {
    fontSize: 14,
    fontWeight: "bold",
    color: COLORS.textDark,
  },
  listTime: {
    fontSize: 11,
    color: COLORS.textDark,
    fontWeight: "500",
  },
  listDetail: {
    fontSize: 11,
    color: COLORS.textDark,
    fontWeight: "500",
  },
  bottomNav: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.white,
    flexDirection: "row",
    justifyContent: "space-around",
    paddingTop: 12,
    paddingBottom: 30,
    borderTopLeftRadius: SIZES.radiusLarge,
    borderTopRightRadius: SIZES.radiusLarge,
    elevation: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
  },
  navItem: {
    alignItems: "center",
    gap: 4,
    width: 80,
  },
  navTextActive: {
    color: COLORS.primary,
    fontSize: 12,
    fontWeight: "500",
  },
  navTextInactive: {
    color: "#8E8E93",
    fontSize: 12,
    fontWeight: "500",
  },
  activeIndicator: {
    width: "100%",
    height: 2,
    backgroundColor: COLORS.primary,
    marginTop: 4,
  },
  inactiveIndicator: {
    width: "100%",
    height: 2,
    backgroundColor: "transparent",
    marginTop: 4,
  },
});
