import { StyleSheet } from "react-native";
import { COLORS, SIZES } from "../constants/themes";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  header: {
    backgroundColor: COLORS.white,
    borderBottomLeftRadius: SIZES.radiusLarge,
    borderBottomRightRadius: SIZES.radiusLarge,
    padding: SIZES.padding,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: SIZES.padding,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  avatarPlaceholder: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: COLORS.primary,
  },
  appName: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.primary,
  },
  appSub: {
    fontSize: 12,
    color: COLORS.textDark,
    opacity: 0.7,
  },
  listWrapper: {
    flex: 1,
    paddingHorizontal: SIZES.padding,
    paddingBottom: 90,
  },
  filterContainer: {
    marginBottom: SIZES.padding,
    gap: 12,
  },
  toggleContainer: {
    flexDirection: "row",
    backgroundColor: "#F0F5FA",
    borderRadius: SIZES.radiusSmall,
    padding: 4,
    width: "100%",
  },
  toggleButton: {
    flex: 1,
    paddingVertical: 8,
    alignItems: "center",
    borderRadius: SIZES.radiusSmall - 2,
  },
  toggleButtonActive: {
    backgroundColor: COLORS.white,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  toggleText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#A0B2C6",
  },
  toggleTextActive: {
    color: COLORS.primary,
  },
  datePickerButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.white,
    paddingVertical: 10,
    borderRadius: SIZES.radiusSmall,
    gap: 8,
    borderWidth: 1,
    borderColor: "#F0F5FA",
  },
  datePickerText: {
    fontSize: 13,
    fontWeight: "500",
    color: COLORS.textDark,
  },
  zoneFilterWrap: {
    gap: 8,
  },
  zoneFilterLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.textDark,
    opacity: 0.8,
  },
  zoneFilterRow: {
    flexDirection: "row",
    backgroundColor: "#F0F5FA",
    borderRadius: SIZES.radiusSmall,
    padding: 4,
    width: "100%",
  },
  zoneChip: {
    flex: 1,
    paddingVertical: 8,
    alignItems: "center",
    borderRadius: SIZES.radiusSmall - 2,
  },
  zoneChipActive: {
    backgroundColor: COLORS.white,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  zoneChipText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#8FA2B6",
  },
  zoneChipTextActive: {
    color: COLORS.primary,
  },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: SIZES.radiusMedium,
    flex: 1,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    overflow: "hidden",
    height: "100%",
  },
  flatListContent: {
    padding: SIZES.padding,
    paddingBottom: SIZES.padding,
  },
  listItem: {
    backgroundColor: "#F9FBFE",
    borderRadius: SIZES.radiusSmall,
    borderWidth: 1,
    borderColor: "#E3ECF6",
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 10,
  },
  itemTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  zonePill: {
    backgroundColor: "#EAF2FC",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
  },
  zonePillText: {
    fontSize: 11,
    fontWeight: "700",
    color: COLORS.primary,
  },
  metricsRow: {
    flexDirection: "row",
    alignItems: "stretch",
  },
  metricBlock: {
    flex: 1,
    gap: 4,
  },
  metricDivider: {
    width: 1,
    backgroundColor: "#E3ECF6",
    marginHorizontal: 10,
  },
  metricLabel: {
    fontSize: 11,
    color: "#8FA2B6",
    fontWeight: "600",
  },
  listTime: {
    fontSize: 12,
    color: "#63778D",
    fontWeight: "500",
  },
  metricValue: {
    fontSize: 13,
    color: COLORS.textDark,
    fontWeight: "700",
  },
  bottomNav: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.white,
    flexDirection: "row",
    justifyContent: "space-around",
    paddingTop: 12,
    paddingBottom: 30,
    borderTopLeftRadius: SIZES.radiusLarge,
    borderTopRightRadius: SIZES.radiusLarge,
    elevation: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
  },
  navItem: {
    alignItems: "center",
    gap: 4,
    width: 80,
  },
  navTextActive: {
    color: COLORS.primary,
    fontSize: 12,
    fontWeight: "500",
  },
  navTextInactive: {
    color: "#8E8E93",
    fontSize: 12,
    fontWeight: "500",
  },
  activeIndicator: {
    width: "100%",
    height: 2,
    backgroundColor: COLORS.primary,
    marginTop: 4,
  },
  inactiveIndicator: {
    width: "100%",
    height: 2,
    backgroundColor: "transparent",
    marginTop: 4,
  },
});
