import { StyleSheet } from "react-native";
import { COLORS, SIZES } from "@constants/themes";

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: "flex-end",
  },
  overlayBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(7, 19, 38, 0.35)",
  },
  overlayPressArea: {
    flex: 1,
  },
  sheet: {
    backgroundColor: COLORS.background,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    maxHeight: "90%",
    paddingHorizontal: SIZES.padding,
    paddingTop: 10,
    paddingBottom: 16,
  },
  grabber: {
    alignSelf: "center",
    width: 56,
    height: 5,
    borderRadius: 4,
    backgroundColor: "#C6D4E3",
    marginBottom: 14,
  },
  sheetHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 14,
  },
  sheetTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: COLORS.secondary,
  },
  sheetSubtitle: {
    fontSize: 12,
    color: COLORS.textDark,
    opacity: 0.65,
    marginTop: 2,
  },
  closeButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#EEF3F9",
    justifyContent: "center",
    alignItems: "center",
  },
  scrollContent: {
    paddingBottom: 36,
    gap: 14,
  },
  heroCard: {
    backgroundColor: COLORS.white,
    borderRadius: SIZES.radiusMedium,
    padding: 16,
    borderWidth: 1,
    borderColor: "#DFE8F2",
    overflow: "hidden",
  },
  statusAccent: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 6,
  },
  heroHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 8,
    marginBottom: 14,
  },
  heroTitle: {
    fontSize: 19,
    fontWeight: "800",
    color: COLORS.secondary,
  },
  heroSubTitle: {
    marginTop: 4,
    fontSize: 12,
    color: COLORS.textDark,
    opacity: 0.7,
  },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
  },
  statusBadgeText: {
    fontSize: 11,
    fontWeight: "700",
  },
  metricsRow: {
    flexDirection: "row",
    gap: 8,
  },
  metricTile: {
    flex: 1,
    backgroundColor: "#F8FAFD",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#ECF1F7",
    padding: 10,
  },
  metricLabel: {
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 0.5,
    color: COLORS.textDark,
    opacity: 0.58,
    marginBottom: 6,
  },
  metricValue: {
    fontSize: 16,
    fontWeight: "800",
    color: COLORS.secondary,
  },
  metricUnit: {
    fontSize: 11,
    color: COLORS.textDark,
    opacity: 0.65,
    fontWeight: "500",
  },
  metaRow: {
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#EEF2F7",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  metaLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  metaTimeText: {
    fontSize: 11,
    color: "#8E8E93",
  },
  metaStatusText: {
    fontSize: 11,
    fontWeight: "700",
  },
  logsSection: {
    backgroundColor: COLORS.white,
    borderRadius: SIZES.radiusMedium,
    borderWidth: 1,
    borderColor: "#DFE8F2",
    padding: 16,
    gap: 10,
  },
  logsTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: COLORS.secondary,
  },
  logsSubtitle: {
    fontSize: 12,
    color: COLORS.textDark,
    opacity: 0.65,
    marginBottom: 4,
  },
  emptyLogsBox: {
    backgroundColor: "#F8FAFD",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E6EEF8",
    paddingVertical: 20,
    alignItems: "center",
  },
  emptyLogsText: {
    fontSize: 12,
    color: "#8194A7",
    fontWeight: "500",
  },
  logItem: {
    backgroundColor: "#F8FAFD",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E6EEF8",
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 10,
  },
  logItemHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  logTime: {
    fontSize: 12,
    color: COLORS.textDark,
    fontWeight: "600",
  },
  logZonePill: {
    backgroundColor: "#EAF2FC",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  logZonePillText: {
    fontSize: 10,
    color: COLORS.primary,
    fontWeight: "700",
  },
  logMetricsRow: {
    flexDirection: "row",
    alignItems: "stretch",
  },
  logMetricCol: {
    flex: 1,
    gap: 4,
  },
  logMetricLabel: {
    fontSize: 10,
    color: "#8DA1B6",
    fontWeight: "600",
  },
  logMetricValue: {
    fontSize: 13,
    color: COLORS.textDark,
    fontWeight: "800",
  },
  logDivider: {
    width: 1,
    backgroundColor: "#DCE8F5",
    marginHorizontal: 10,
  },
});
