import { StyleSheet } from "react-native";
import { colors } from "@/constants/colors";
import { fontSize } from "@/constants/typography";

export const headerStyles = StyleSheet.create({
  // Heading
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  shadowWrapper: {
    backgroundColor: "transparent",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    position: "relative",
    elevation: 5,
  },
  header: {
    display: "flex",
    flexDirection: "column",
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    backgroundColor: "#fff",
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    paddingTop: 150,
    height: 150,
  },
  topPart: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
    position: "absolute",
    top: 0,
    right: 0,
    left: 0,
    height: 150,
    backgroundColor: "#fff",
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    width: "100%",
  },
  pictureHolder: {
    backgroundColor: "#dcdc",
    width: 50,
    height: 50,
    borderRadius: 25,
  },
  middlePart: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: 12,
    width: 230,
    height: 100,
  },
  appName: {
    width: "100%",
    fontSize: fontSize.title,
    color: colors.primary,
    fontWeight: "bold",
    marginBottom: 4,
  },
  appDescription: {
    width: "100%",
    fontSize: fontSize.subtitle,
    color: colors.secondary,
  },
  chevronButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  expandedHeader: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: 12,
    alignSelf: "center",
    width: "100%",
  },
  navigation: {
    fontSize: fontSize.subtitle,
    color: colors.primary,
    marginBottom: 8,
    textAlign: "left",
  },
});
